WebUI/Snapcode.WebUI.Site/Models/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Snapcode.WebUI.Site.Models
{
    public class SearchViewModel
    {
        public SearchViewModel()
        {
            Profiles = new List<Model.Profile>();
            Hashtags = new List<Model.Hashtag>();
        }

        public List<Model.Profile> Profiles { get; set; }
        public List<Model.Hashtag> Hashtags { get; set; }
        public string Query { get; set; }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/CategoryController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using Snapcode.WebUI.Site.Models;
    using System.Linq;

    public class CategoryController : Controller
    {
        ProfileData _profileData;
        CategoryData _categoryData;
        Infrastructure.Cache.CacheHelper _cacheHelper;

        public CategoryController(ProfileData _profileData
            , CategoryData _categoryData
            , Infrastructure.Cache.CacheHelper _cacheHelper
            )
        {
            this._profileData = _profileData;
            this._categoryData = _categoryData;
            this._cacheHelper = _cacheHelper;
        }

        public IActionResult Index(string slug, int page=1)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { q = "slug-empty" });

            var category = _cacheHelper.Categories.Where(x => x.Slug == slug).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Index", "Home", new { q = "category-not-found" });

            var model = new CategoryViewModel()
            {
                Category = category,
            };

            var profiles = _profileData.GetByPage(x => x.CategoryId == category.Id, page, 15);
            var totalItem = _profileData.GetCount(x => x.CategoryId == category.Id);

            model.Profiles = profiles;
            model.TotalCount = totalItem;
            model.TotalPage = totalItem / 15;
            model.TotalPage++;
            model.Page = page;

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/HashtagController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using Snapcode.WebUI.Site.Models;
    using System;
    using System.Linq;

    public class HashtagController : Controller
    {
        ProfileData _profileData;
        HashtagData _hashtagData;
        Infrastructure.Cache.CacheHelper _cacheHelper;

        public HashtagController(ProfileData _profileData
            , HashtagData _hashtagData
            , Infrastructure.Cache.CacheHelper _cacheHelper
            )
        {
            this._profileData = _profileData;
            this._hashtagData = _hashtagData;
            this._cacheHelper = _cacheHelper;
        }

        public IActionResult Index(string slug, int page=1)
        {
            var name = slug;
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { q = "hashtag-empty" });

            var hashtag = _hashtagData.GetBy(x => x.Name == slug).FirstOrDefault();
            if (hashtag == null)
            {
                if (slug.Contains(" "))
                    name = slug.Split(' ')[0];
                else
                    name = slug;

                var hModel = new Model.Hashtag()
                {
                    isBan = false,
                    Name = name,
                    IsDmca = false,
                };

                var insert = _hashtagData.Insert(hModel);
                if (!insert.IsSucceed)
                    return RedirectToAction("Index", "Home", new { q = "hashtag-not-found" });

                hashtag = hModel;
            }

            if (hashtag.IsDmca)
                name = "funny";

            var model = new HashtagViewModel()
            {
                Hashtag = hashtag,
            };

            var profiles = _profileData.GetByPage(x => x.Interests.Contains(name), page, 15);
            var totalItem = _profileData.GetCount(x => x.Interests.Contains(name));

            if (profiles.Count <= 0)
            {
                profiles = _cacheHelper.Profiles.OrderBy(x=> Guid.NewGuid()).Take(18).ToList();
            }

            model.Tag = name;
            model.Profiles = profiles;
            model.TotalCount = totalItem;
            model.TotalPage = totalItem / 15;
            model.TotalPage++;
            model.Page = page;

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/SearchController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using Snapcode.WebUI.Site.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public class SearchController : Controller
    {
        ProfileData _profileData;
        HashtagData _hashtagData;

        public SearchController(ProfileData _profileData
            , HashtagData _hashtagData
            )
        {
            this._profileData = _profileData;
            this._hashtagData = _hashtagData;
        }

        public IActionResult Index(string query)
        {
            if (string.IsNullOrEmpty(query))
                return RedirectToAction("Index", "Home", new { q = "query-empty" });

            var profiles = _profileData.GetBy(x => x.Username.Contains(query));
            var hashtags = _hashtagData.GetBy(x => x.Name.Contains(query));

            var model = new SearchViewModel()
            {
                Hashtags = hashtags,
                Profiles = profiles,
                Query = query,
            };

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Views/Search/Index.cshtml
@model SearchViewModel
@{
    ViewBag.Title = $"Search for Snapchat Users & Hashtags & Medias | ";
    ViewBag.Description = $"Search for Snapchat Users & Hashtags & Medias | ";
    ViewBag.Robots = "noindex,follow";
    ViewBag.Canonical = head.Canonical("Index", "Search", new { query = Model.Query });
}

<div class="container">
    <div class="col-8">
        <h3 class="box-title">@Model.Query Search Results</h3>
        <div class="grid-box">
            <div class="column-list-2">
                <div class="col-item">
                    <h3 class="box-title">Hastag Result</h3>
                    <div class="box-categories">
                        <ul>
                            @foreach (var item in Model.Hashtags)
                            {
                                <li><a href="@Url.Action("Index","Hashtag", new { slug = item.Name.ToLower() })" title="@seo.HashtagHrefText(item.Name)">@item.Name</a></li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="col-item">
                    <h3 class="box-title">Account Result</h3>
                    <div class="box-categories">
                        <ul>
                            @foreach (var item in Model.Profiles)
                            {
                                var fullname = item.FirstName + " " + item.LastName;
                                if (string.IsNullOrEmpty(fullname))
                                { fullname = item.Username; }

                                <li><a href="@Url.Action("Index","Profile", new { username = item.Username })" title="@seo.ProfileUserHref(item.Username, fullname)">@fullname</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4 aside">
        <div class="sidebar-sticky">
            <div id="sidebar" class="absolute">
                <div class="widget">
                    <h3 class="widget-title">Quick Search</h3>
                    <div class="aside-search">
                        <input class="form-control" type="text" id="asideInput" value="@Model.Query" placeholder="Search" aria-label="Search">
                        <button class="aside-search-button" id="asideButton" aria-label="Search"><i class="icon-search"></i></button>
                    </div>
                </div>
                <div class="widget">
                    <h3 class="widget-title">Quick Search</h3>
                    <div class="ads">
                        <div></div>
                    </div>
                </div>
                <div class="widget">
                    <h3 class="widget-title">Lists</h3>
                    <ul class="widget-categories">
                        @foreach (var item in cache.Lists.OrderBy(x => Guid.NewGuid()).Take(15))
                        {
                            <li><a href="@Url.Action("Index","Category", new { slug = item.Slug })" title="@seo.CategoryHrefText(item.Name)">@item.Name</a></li>
                        }
                    </ul>
                </div>
                <div class="widget">
                    <h3 class="widget-title">Categories</h3>
                    <ul class="widget-categories">
                        @foreach (var item in cache.Categories.OrderBy(x => Guid.NewGuid()).Take(15))
                        {
                            <li><a href="@Url.Action("Index","Category", new { slug = item.Slug })" title="@seo.CategoryHrefText(item.Name)">@item.Name</a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>