WebUI/Snapcode.WebUI.Site/Controllers/CategoryController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using Snapcode.WebUI.Site.Models;
    using System.Linq;

    public class CategoryController : Controller
    {
        ProfileData _profileData;
        CategoryData _categoryData;
        Infrastructure.Cache.CacheHelper _cacheHelper;

        public CategoryController(ProfileData _profileData
            , CategoryData _categoryData
            , Infrastructure.Cache.CacheHelper _cacheHelper
            )
        {
            this._profileData = _profileData;
            this._categoryData = _categoryData;
            this._cacheHelper = _cacheHelper;
        }

        public IActionResult Index(string slug, int page=1)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { q = "slug-empty" });

            var category = _cacheHelper.Categories.Where(x => x.Slug == slug).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Index", "Home", new { q = "category-not-found" });

            var model = new CategoryViewModel()
            {
                Category = category,
            };

            var profiles = _profileData.GetByPage(x => x.CategoryId == category.Id, page, 15);
            var totalItem = _profileData.GetCount(x => x.CategoryId == category.Id);

            model.Profiles = profiles;
            model.TotalCount = totalItem;
            model.TotalPage = totalItem / 15;
            model.TotalPage++;
            model.Page = page;

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/ListController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using Snapcode.WebUI.Site.Models;
    using System.Linq;

    public class ListController : Controller
    {
        PopularData _popularData;
        Infrastructure.Cache.CacheHelper _cacheHelper;

        public ListController(PopularData _popularData
            , Infrastructure.Cache.CacheHelper _cacheHelper
            )
        {
            this._popularData = _popularData;
            this._cacheHelper = _cacheHelper;
        }

        public IActionResult Index(string slug, int page=1)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { q = "slug-empty" });

            var list = _cacheHelper.Lists.Where(x => x.Slug == slug).FirstOrDefault();
            if (list == null)
                return RedirectToAction("Index", "Home", new { q = "list-not-found" });

            var model = new ListViewModel()
            {
                List = list,
            };

            var profiles = _popularData.GetByPage(x => x.ListId == list.Id, page, 15);
            var totalItem = _popularData.GetCount(x => x.ListId == list.Id);

            model.Populars = profiles;
            model.TotalCount = totalItem;
            model.TotalPage = totalItem / 15;
            model.TotalPage++;
            model.Page = page;

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/RemoveController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using System.Collections.Generic;
    using System.Linq;

    public class RemoveController : Controller
    {
        RemovalData _removalData;

        public RemoveController(RemovalData _removalData)
        {
            this._removalData = _removalData;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new Model.Removal();
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(string username, string email, string message, string link)
        {
            var errors = new List<string>();

            if (string.IsNullOrEmpty(username)) errors.Add("username is required");
            if (string.IsNullOrEmpty(email)) errors.Add("email is required");
            if (string.IsNullOrEmpty(message)) errors.Add("message is required");
            if (string.IsNullOrEmpty(link)) errors.Add("link is required");

            var remoteIpAddress = Request.HttpContext.Connection.RemoteIpAddress;

            var model = new Model.Removal()
            {
                Description = message,
                IsDeleted = false,
                IsDmca = false,
                IsRead = false,
                Mail = email,
                Username = username,
                Url = link,
                IpAddress = remoteIpAddress.ToString(),
            };

            if (errors.Count > 0)
            {
                ViewBag.IsSucceed = false;
                ViewBag.Message = errors[0];
                return View(model);
            }

            var insert = _removalData.Insert(model);
            if (insert.IsSucceed)
            {
                ViewBag.IsSucceed = true;
                ViewBag.Message = "Will be able to remove it as soon as possible";
                return View(model);
            }

            ViewBag.IsSucceed = false;
            ViewBag.Message = insert.Message;

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Views/Page/About.cshtml
@{
    ViewBag.Title = $"About | {cache.Setting.Sitename}";
    ViewBag.Description = $"About | {cache.Setting.Sitename}";
    ViewBag.Robots = "noindex, nofollow";
    ViewBag.Canonical = head.Canonical("About", "Page");
}

<div class="container">
    <div class="col-8">
        <h3 class="box-title">Privacy Policy</h3>
        <div class="grid-box">
            <div class="page-desc">
                <p>
                    @cache.Setting.Sitename is the ultimate directory to discover interesting Snapchat users to follow
                </p>
                <h3>Delete Content</h3>
                <p>If you wish to be removed from @cache.Setting.Sitename please visit <a href="@Url.Action("Index","Remove")">Remove Content</a></p>
                <h3>Overview</h3>
                <p>@cache.Setting.Sitename is a directory of Snapchat users. It let's you easily discover new people on Snapchat that may be of interest to you. It does so by providing a searchable database of interesting people who use Snapchat, including their username, snapcode, some snaps, related accounts, and more, giving you a better glimpse of what's out there.</p>
                <p>@cache.Setting.Sitename is a collective index with a snappy twist, hence the name @cache.Setting.Sitename. Anyone can add and edit content on the site. Content on @cache.Setting.Sitename is 100% user-generated. To add a user to @cache.Setting.Sitename, start on the <a href="@Url.Action("Add","Profile")">submission page</a>. Our aim is to be a sort of Pokédex, but for Snapchat. Please note that @cache.Setting.Sitename is not affiliated with Snapchat.</p>
                <h3>Contact us</h3>
                <p>If you need our help, please contact @cache.Setting.Sitename team by the following contact information.</p>
                <p>(Note: please change "#" to "@@") sg.snapybox#gmail.com</p>
                <h3>We are social</h3>
                <p>@cache.Setting.Sitename participates in a variety of affiliate programs, often related to entertainment. This means that when you click on an affiliate link, @cache.Setting.Sitename earns a commission on your purchase. These commissions help us to earn an income from our website. In particular, the Amazon Associates program requires that we let you know that: As an Amazon Associate we earn from qualifying purchases.</p>
                <h3>We are social</h3>
                <p>Connect, follow and have a conversation with us.</p>
            </div>
        </div>
    </div>
    <div class="col-4 aside">
        <div class="sidebar-sticky">
            <div id="sidebar" class="absolute">
                <div class="widget">
                    <h3 class="widget-title">Quick Search</h3>
                    <div class="aside-search">
                        <input class="form-control" type="text" id="asideInput" placeholder="Search" aria-label="Search">
                        <button class="aside-search-button" id="asideButton" aria-label="Search"><i class="icon-search"></i></button>
                    </div>
                </div>
                @if (cache.AdsAccounts != null)
                {
                    if (!string.IsNullOrEmpty(cache.AdsAccounts.Ads336x280))
                    {
                        <div class="widget">
                            <h3 class="widget-title">Sponsored</h3>
                            <div class="ads">
                                @cache.AdsAccounts.Ads336x280
                            </div>
                        </div>
                    }
                }
                <div class="widget">
                    <h3 class="widget-title">Lists</h3>
                    <ul class="widget-categories">
                        @foreach (var item in cache.Lists.OrderBy(x => Guid.NewGuid()).Take(15))
                        {
                            <li><a href="@Url.Action(" Index","List", new { slug=item.Slug })" title="@seo.CategoryHrefText(item.Name)">@item.Name</a></li>
                        }
                    </ul>
                </div>
                <div class="widget">
                    <h3 class="widget-title">Categories</h3>
                    <ul class="widget-categories">
                        @foreach (var item in cache.Categories.OrderBy(x => Guid.NewGuid()).Take(15))
                        {
                            <li><a href="@Url.Action(" Index","Category", new { slug=item.Slug })" title="@seo.CategoryHrefText(item.Name)">@item.Name</a></li>
                        }
                    </ul>
                </div>
                @if (cache.AdsAccounts != null)
                {
                    if (!string.IsNullOrEmpty(cache.AdsAccounts.Ads300x600))
                    {
                        <div class="widget">
                            <h3 class="widget-title">Sponsored</h3>
                            <div class="ads">
                                @cache.AdsAccounts.Ads300x600
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>