WebUI/Snapcode.WebUI.Site/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Snapcode.WebUI.Site.Models
{
    public class HomeViewModel
    {
        public HomeViewModel()
        {
            Profiles = new List<Model.Profile>();
        }

        public List<Model.Profile> Profiles { get; set; }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/CategoryController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using Snapcode.WebUI.Site.Models;
    using System.Linq;

    public class CategoryController : Controller
    {
        ProfileData _profileData;
        CategoryData _categoryData;
        Infrastructure.Cache.CacheHelper _cacheHelper;

        public CategoryController(ProfileData _profileData
            , CategoryData _categoryData
            , Infrastructure.Cache.CacheHelper _cacheHelper
            )
        {
            this._profileData = _profileData;
            this._categoryData = _categoryData;
            this._cacheHelper = _cacheHelper;
        }

        public IActionResult Index(string slug, int page=1)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { q = "slug-empty" });

            var category = _cacheHelper.Categories.Where(x => x.Slug == slug).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Index", "Home", new { q = "category-not-found" });

            var model = new CategoryViewModel()
            {
                Category = category,
            };

            var profiles = _profileData.GetByPage(x => x.CategoryId == category.Id, page, 15);
            var totalItem = _profileData.GetCount(x => x.CategoryId == category.Id);

            model.Profiles = profiles;
            model.TotalCount = totalItem;
            model.TotalPage = totalItem / 15;
            model.TotalPage++;
            model.Page = page;

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/HomeController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using System.Linq;

    public class HomeController : Controller
    {
        ProfileData profileData;
        Infrastructure.Cache.CacheHelper _cacheHelper;

        public HomeController(ProfileData profileData, Infrastructure.Cache.CacheHelper _cacheHelper)
        {
            this.profileData = profileData;
            this._cacheHelper = _cacheHelper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult ClearSetting()
        {
            _cacheHelper.SettingClear();
            return Json(new { result = true });
        }

        public JsonResult ClearCategory()
        {
            _cacheHelper.CategoriesClear();
            return Json(new { result = true });
        }

        public JsonResult ClearProfile()
        {
            _cacheHelper.ProfilesClear();
            return Json(new { result = true });
        }

        public JsonResult ClearList()
        {
            _cacheHelper.ListsClear();
            return Json(new { result = true });
        }

        public JsonResult ClearPopular()
        {
            _cacheHelper.PopularAccountClear();
            return Json(new { result = true });
        }

        public JsonResult ClearAds()
        {
            _cacheHelper.AdsAccountClear();
            return Json(new { result = true });
        }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/ListController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using Snapcode.WebUI.Site.Models;
    using System.Linq;

    public class ListController : Controller
    {
        PopularData _popularData;
        Infrastructure.Cache.CacheHelper _cacheHelper;

        public ListController(PopularData _popularData
            , Infrastructure.Cache.CacheHelper _cacheHelper
            )
        {
            this._popularData = _popularData;
            this._cacheHelper = _cacheHelper;
        }

        public IActionResult Index(string slug, int page=1)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { q = "slug-empty" });

            var list = _cacheHelper.Lists.Where(x => x.Slug == slug).FirstOrDefault();
            if (list == null)
                return RedirectToAction("Index", "Home", new { q = "list-not-found" });

            var model = new ListViewModel()
            {
                List = list,
            };

            var profiles = _popularData.GetByPage(x => x.ListId == list.Id, page, 15);
            var totalItem = _popularData.GetCount(x => x.ListId == list.Id);

            model.Populars = profiles;
            model.TotalCount = totalItem;
            model.TotalPage = totalItem / 15;
            model.TotalPage++;
            model.Page = page;

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/PopularController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using Snapcode.WebUI.Site.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public class PopularController : Controller
    {
        PopularData _popularData;
        ReviewData _reviewData;

        public PopularController(PopularData _popularData
            , ReviewData _reviewData
            )
        {
            this._popularData = _popularData;
            this._reviewData = _reviewData;
        }

        public IActionResult Index(string username)
        {
            if (string.IsNullOrEmpty(username))
                return RedirectToAction("Index", "Home", new { q = "username-empty" });

            var profile = _popularData.GetBy(x => x.Username == username).FirstOrDefault();
            if (profile == null)
                return RedirectToAction("Index", "Home", new { q = "profile-not-found" });

            var reviews = _reviewData.GetBy(x => x.UserId == profile.Id && x.IsPopular && x.IsActive);

            var model = new PopularViewModel()
            {
                Profile = profile,
                Relateds = _popularData.GetBy(x=>x.ListId == profile.ListId).OrderBy(x=> Guid.NewGuid()).Take(9).ToList(),
                Reviews = reviews,
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(int Point, string Review, string Fullname, string Email, int ProfileId)
        {
            var errors = new List<string>();
            if (Point <= 0) errors.Add("Please select any point");
            if (string.IsNullOrEmpty(Review)) errors.Add("Comment input required");
            if (string.IsNullOrEmpty(Fullname)) errors.Add("Fullname input required");
            if (string.IsNullOrEmpty(Email)) errors.Add("Email input required");

            var profile = _popularData.GetByKey(ProfileId);
            if (profile == null)
                return RedirectToAction("Index", "Home", new { q = "not_found_profile" });

            if (errors.Count > 0)
            {
                ViewBag.Error = errors;
                return RedirectToAction("Index", "Profile", new { username = profile.Username, q = "inputs required" });
            }

            var review = new Model.Review()
            {
                CreateDate = DateTime.Now,
                Description = Review,
                Fullname = Fullname,
                IsActive = true,
                IsPopular = false,
                IsRead = false,
                Star = Point,
                UserId = ProfileId,
                Email = Email,
            };

            var insert_review = _reviewData.Insert(review);
            if (insert_review.IsSucceed)
                return RedirectToAction("Index", "Profile", new { username = profile.Username, q = "review-sended" });

            errors.Add("Server Error Please Later Try Again");
            return RedirectToAction("Index", "Profile", new { username = profile.Username, q = "server-error" });
        }
    }
}

WebUI/Snapcode.WebUI.Site/Views/Home/Index.cshtml
@{
    ViewBag.Title = cache.Setting.SiteHomeTitle;
    ViewBag.Description = cache.Setting.SiteHomeDesription;
    ViewBag.Robots = "index,follow";
    ViewBag.Canonical = head.Canonical("Index", "Home");
}

<div class="container">
    <div class="col-8">
        <h3 class="box-title">Featureds</h3>
        <div class="grid-box">
            <div class="featured-box">
                <div>
                    <h3>Add Me</h3>
                    <p>By adding your own account, you can make friends with new people and communicate with people with the hashtag you love.</p>
                </div>
                <div>
                    <h3>Categorized</h3>
                    <p>It is a system where you can easily find and follow popular Snapchat users, famous players or famous social media phenomena. This system has nothing to do with snapchat, users who are here may not be on snapchat</p>
                </div>
                <div>
                    <h3>Discover</h3>
                    <p>Thanks to its easy use, you can add your account and discover the accounts you want to follow later. You can make new friends with special lists listed in accordance with the criteria you are looking for.</p>
                </div>
            </div>

            <div class="column-list-2">
                <div class="col-item">
                    <h3 class="box-title">Snapchat Categories</h3>
                    <div class="box-categories">
                        <ul>
                            @foreach (var item in cache.Categories.OrderBy(x => Guid.NewGuid()).Take(7))
                            {
                                <li><a href="@Url.Action("Index","Category", new { slug = item.Slug })" title="@seo.CategoryHrefText(item.Name)">@item.Name</a></li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="col-item">
                    <h3 class="box-title">Account Lists</h3>
                    <div class="box-categories">
                        <ul>
                            @foreach (var item in cache.Lists.OrderBy(x => Guid.NewGuid()).Take(7))
                            {
                                <li><a href="@Url.Action("Index","List", new { slug = item.Slug })" title="@seo.ListHrefText(item.Name)">@item.Name</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>

            <h3 class="box-title mt-5">Popular Accounts</h3>
            <div class="accounts-box">
                @foreach (var item in cache.PopularAccounts.OrderBy(x => Guid.NewGuid()).Take(6))
                {
                    <div class="account-item">
                        <div class="image">
                            <a href="@Url.Action("Index","Popular", new { username = item.Username })" title="@seo.PopularUserHref(item.Username,item.Fullname)">
                                <picture>
                                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII="
                                         lazy-src="@item.Picture" width="100" height="100" 
                                         onerror="this.src='/_assets/images/not_found.png'"
                                         alt="@seo.PopularUserImage(item.Username,item.Fullname)" title="@seo.PopularUserImage(item.Username,item.Fullname)">
                                </picture>
                            </a>
                        </div>
                        <div class="account-info">
                            <h3><a href="@Url.Action("Index","Popular", new { username = item.Username })" title="@seo.PopularUserHref(item.Username,item.Fullname)">@item.Fullname</a></h3>
                            <p>@@@item.Username</p>
                        </div>
                    </div>
                }
            </div>
            <h3 class="box-title mt-5">New Register Accounts</h3>
            <div class="accounts-box">
                @foreach (var item in cache.Profiles.OrderBy(x => Guid.NewGuid()).Take(6))
                {
                    var fullname = item.FirstName + " " + item.LastName;
                    <div class="account-item">
                        <div class="image">
                            <a href="@Url.Action("Index","Profile", new { username = item.Username })" title="@seo.ProfileUserHref(item.Username, fullname)">
                                <picture>
                                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII="
                                         onerror="this.src='/_assets/images/not_found.png'"
                                         lazy-src="@item.BoorCode" width="100" height="100" 
                                         alt="@seo.ProfileUserImage(item.Username,fullname,item.About)" title="@seo.ProfileUserImage(item.Username,fullname,item.About)">
                                </picture>
                            </a>
                        </div>
                        <div class="account-info">
                            <h3><a href="@Url.Action("Index","Profile", new { username = item.Username })" title="@seo.ProfileUserHref(item.Username, fullname)">@item.FirstName @item.LastName</a></h3>
                            <p>@@@item.Username</p>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-4 aside">
        <div class="sidebar-sticky">
            <div id="sidebar" class="absolute">
                <div class="widget">
                    <h3 class="widget-title">Quick Search</h3>
                    <div class="aside-search">
                        <input class="form-control" type="text" id="asideInput" placeholder="Search" aria-label="Search">
                        <button class="aside-search-button" id="asideButton" aria-label="Search"><i class="icon-search"></i></button>
                    </div>
                </div>
                @if (cache.AdsAccounts != null)
                {
                    if (!string.IsNullOrEmpty(cache.AdsAccounts.Ads336x280))
                    {
                        <div class="widget">
                            <h3 class="widget-title">Sponsored</h3>
                            <div class="ads">
                                @cache.AdsAccounts.Ads336x280
                            </div>
                        </div>
                    }
                }
                <div class="widget">
                    <h3 class="widget-title">Lists</h3>
                    <ul class="widget-categories">
                        @foreach (var item in cache.Lists.OrderBy(x => Guid.NewGuid()).Take(15))
                        {
                            <li><a href="@Url.Action("Index","List", new { slug = item.Slug })" title="@seo.CategoryHrefText(item.Name)">@item.Name</a></li>
                        }
                    </ul>
                </div>
                <div class="widget">
                    <h3 class="widget-title">Categories</h3>
                    <ul class="widget-categories">
                        @foreach (var item in cache.Categories.OrderBy(x => Guid.NewGuid()).Take(15))
                        {
                            <li><a href="@Url.Action("Index","Category", new { slug = item.Slug })" title="@seo.CategoryHrefText(item.Name)">@item.Name</a></li>
                        }
                    </ul>
                </div>
                @if (cache.AdsAccounts != null)
                {
                    if (!string.IsNullOrEmpty(cache.AdsAccounts.Ads300x600))
                    {
                        <div class="widget">
                            <h3 class="widget-title">Sponsored</h3>
                            <div class="ads">
                                @cache.AdsAccounts.Ads300x600
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>