WebUI/Snapcode.WebUI.Site/Controllers/PageController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using System.Linq;

    public class PageController : Controller
    {
        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

WebUI/Snapcode.WebUI.Site/Controllers/RemoveController.cs
namespace Snapcode.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Snapcode.Data;
    using System.Collections.Generic;
    using System.Linq;

    public class RemoveController : Controller
    {
        RemovalData _removalData;

        public RemoveController(RemovalData _removalData)
        {
            this._removalData = _removalData;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new Model.Removal();
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(string username, string email, string message, string link)
        {
            var errors = new List<string>();

            if (string.IsNullOrEmpty(username)) errors.Add("username is required");
            if (string.IsNullOrEmpty(email)) errors.Add("email is required");
            if (string.IsNullOrEmpty(message)) errors.Add("message is required");
            if (string.IsNullOrEmpty(link)) errors.Add("link is required");

            var remoteIpAddress = Request.HttpContext.Connection.RemoteIpAddress;

            var model = new Model.Removal()
            {
                Description = message,
                IsDeleted = false,
                IsDmca = false,
                IsRead = false,
                Mail = email,
                Username = username,
                Url = link,
                IpAddress = remoteIpAddress.ToString(),
            };

            if (errors.Count > 0)
            {
                ViewBag.IsSucceed = false;
                ViewBag.Message = errors[0];
                return View(model);
            }

            var insert = _removalData.Insert(model);
            if (insert.IsSucceed)
            {
                ViewBag.IsSucceed = true;
                ViewBag.Message = "Will be able to remove it as soon as possible";
                return View(model);
            }

            ViewBag.IsSucceed = false;
            ViewBag.Message = insert.Message;

            return View(model);
        }
    }
}

WebUI/Snapcode.WebUI.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <meta name="description" content="@ViewBag.Description" />
    <meta name="robots" content="@Html.Raw(ViewBag.Robots == null ? "index,follow" : ViewBag.Robots)" />

    <meta name="twitter:title" content="@ViewBag.Title" />
    <meta name="twitter:description" content="@ViewBag.Description" />

    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:description" content="@ViewBag.Description" />

    @if (ViewBag.Canonical != null)
    {
        <link rel="canonical" href="@ViewBag.Canonical" />
        <meta property="og:url" content="@ViewBag.Canonical" />
    }



    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

    <meta property="og:site_name" content="@ViewBag.Title" />
    <meta property="og:type" content="website" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:domain" content="@cache.Setting.Siteurl" />

    <link href="~/_assets/css/style.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">

    @if (!string.IsNullOrEmpty(cache.Setting.HeaderCode))
    {
        @Html.Raw(cache.Setting.HeaderCode);
    }

    @RenderSection("styles", false)

</head>
<body>

    <div class="search-container">
        <div class="search-overlay">
            <div class="search-close">x</div>
            <div>
                <input type="text" placeholder="Search" id="msInput" aria-label="Search">
                <button aria-label="Search" id="msButton"><i class="icon-search"></i></button>
            </div>
        </div>
    </div>

    <header>
        <div class="top-header">
            <div class="container">
                <div class="d-flex-list">
                    <div>
                        <a href="/" title="@cache.Setting.SiteHomeTitle">Home Page</a>
                    </div>
                    <div>
                        <ul class="list-horizontal">
                            @if (!string.IsNullOrEmpty(cache.Setting.Facebook))
                            {
                                <li><a href="https://facebook.com/@cache.Setting.Facebook" title="Facebook" target="_blank" rel="noopener noreferrer"><i class="icon-facebook"></i></a></li>
                            }
                            @if (!string.IsNullOrEmpty(cache.Setting.Instagram))
                            {
                                <li><a href="https://instagram.com/@cache.Setting.Instagram" title="Instagram" target="_blank" rel="noopener noreferrer"><i class="icon-instagram"></i></a></li>
                            }
                            @if (!string.IsNullOrEmpty(cache.Setting.Twitter))
                            {
                                <li><a href="https://twitter.com/@cache.Setting.Twitter" title="Twitter" target="_blank" rel="noopener noreferrer"><i class="icon-twitter"></i></a></li>
                            }
                            @if (!string.IsNullOrEmpty(cache.Setting.Youtube))
                            {
                                <li><a href="https://youtube.com/@cache.Setting.Youtube" title="Youtube" target="_blank" rel="noopener noreferrer"><i class="icon-youtube"></i></a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="logo">
                <a href="/" title="hometitle">
                    <picture>
                        <source srcset="~/_assets/images/logo.webp" type="image/webp">
                        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII="
                             lazy-src="~/_assets/images/logo.png" width="300" height="49" alt="@cache.Setting.SiteHomeTitle" title="@cache.Setting.SiteHomeTitle">
                    </picture>
                </a>
            </div>
        </div>

        <div class="header-menu">
            <div class="container">
                <ul class="menu-list">
                    <li class="menu-item"><a class="nav-link" href="/">Home</a></li>
                    <li class="menu-item"><a class="nav-link" href="@Url.Action("Add","Profile")">Add Me</a></li>
                    <li class="menu-item"><a class="nav-link" href="@Url.Action("Privacy","Page")">Privacy</a></li>
                    <li class="menu-item"><a class="nav-link" href="@Url.Action("About","Page")">About</a></li>
                    <li class="menu-item"><a class="nav-link" href="@Url.Action("Index","Remove")">Remove Me</a></li>
                </ul>
                <div class="menu-items">
                    <div class="menu_icon" id="menuOpener">
                        <i class="icon-list"></i>
                    </div>
                    <div class="search" id="searchOpener">
                        <i class="icon-search"></i>
                    </div>
                </div>
            </div>
        </div>
    </header>

    @RenderBody()

    <footer class="mt-5 footer">
        <div class="container">
            <div class="d-flex-list">
                <div>
                    Tüm Hakları Saklıdır
                </div>
                <div>
                    <ul class="list-horizontal">
                        <li><a href="@Url.Action("Index","Remove")" title="Remove Me">Reemove Me</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <div class="cookie-box">
        <div class="cookie-text">
            <p>By clicking “Allow All”, you agree to the storing of cookies on your device to enhance site navigation, analyze site usage, and assist in our marketing efforts.</p>
        </div>
        <div class="cookie-button">
            <button id="accept-cookie">Allow</button>
            <button id="close-cookie">Disable</button>
        </div>
    </div>

    <div class="menu-container">
        <div class="menu-overlay">
            <div class="menu-close" id="closeMenu"> Close </div>
            <div class="side-menu">
                <ul>
                    <li class="menu-item"><a class="nav-link" href="/">Home</a></li>
                    <li class="menu-item"><a class="nav-link" href="@Url.Action("Add","Profile")">Add Me</a></li>
                    <li class="menu-item"><a class="nav-link" href="@Url.Action("Privacy","Page")">Privacy</a></li>
                    <li class="menu-item"><a class="nav-link" href="@Url.Action("About","Page")">About</a></li>
                    <li class="menu-item"><a class="nav-link" href="@Url.Action("Index","Remove")">Remove Me</a></li>
                </ul>
            </div>
            <ul class="list-social-horizontal">
                @if (!string.IsNullOrEmpty(cache.Setting.Facebook))
                {
                    <li><a href="https://facebook.com/@cache.Setting.Facebook" title="Facebook" target="_blank" rel="noopener noreferrer"><i class="icon-facebook_white"></i></a></li>
                }
                @if (!string.IsNullOrEmpty(cache.Setting.Instagram))
                {
                    <li><a href="https://instagram.com/@cache.Setting.Instagram" title="Instagram" target="_blank" rel="noopener noreferrer"><i class="icon-instagram_white"></i></a></li>
                }
                @if (!string.IsNullOrEmpty(cache.Setting.Twitter))
                {
                    <li><a href="https://twitter.com/@cache.Setting.Twitter" title="Twitter" target="_blank" rel="noopener noreferrer"><i class="icon-twitter_white"></i></a></li>
                }
                @if (!string.IsNullOrEmpty(cache.Setting.Youtube))
                {
                    <li><a href="https://youtube.com/@cache.Setting.Youtube" title="Youtube" target="_blank" rel="noopener noreferrer"><i class="icon-youtube_white"></i></a></li>
                }
            </ul>
        </div>
    </div>


    <script src="~/_assets/js/site.js" defer></script>

    <script type="text/javascript" defer>
        var link = document.createElement("link");
        link.href = "https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap&subset=latin-ext";
        link.type = "text/css";
        link.rel = "stylesheet";
        document.getElementsByTagName("head")[0].appendChild(link);
    </script>

    @RenderSection("scripts", false)

    @if (!string.IsNullOrEmpty(cache.Setting.FooterCode))
    {
        @Html.Raw(cache.Setting.FooterCode);
    }
</body>
</html>